version: "3.7"
services:
  innosig_frontend_webapp:
    container_name: innosig_frontend_webapp
    build:
      context: .
      dockerfile: Dockerfile
    image: innosig_frontend_webapp
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - external-network

networks:
  external-network:
    external:
      name: innosig-backend-backtesting_internal-network