version: "3.7"
services:
  iqoption_frontend_webapp:
    container_name: iqoption_frontend_webapp
    build:
      context: .
      dockerfile: Dockerfile
    image: iqoption_frontend_webapp
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - external-network

networks:
  external-network:
    external:
      name: innosig-iqoption-trader_internal-network